StanfordLegion/legion

runtime/runtime.cc
This typo prevented the runtime from building (and subsequently the entire application), so I think it's a good fix!
=> Fixed typo in runtime

runtime/legion.h
The CArrayLinearization changes all colors of multi-dimenional points to be one dimensional, which breaks the code that uses a multi-dimensional Blockify mapping functor. @lightsighter should confirm that this is a valid fix.
=> runtime: eliminating weird linearization from n-D points to 1D points

runtime/channel.cc, runtime/channel.h, runtime/lowlevel.cc, runtime/lowlevel_disk.cc, runtime/lowlevel_dma.cc, runtime/realm/idx_impl.cc, runtime/realm/mem_impl.h
1) Fix merge issue where HDFMemory locks got left out
2) Change hdf_metadata to hdf_metadata_vec for clarity
3) Implement fix for PriorityXferDesQueue, reverting back to std::set and using a comparitor that provides unique keys and total ordering
=> Fix DMA/master merge, change priorityxferdesqueue comparitor 

runtime/channel.cc
The comparator references `XferDes.priority` during `erase` so it should
be deleted after erasure.
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
=> channel: fix use after delete

runtime/realm/threads.cc, runtime/runtime.mk
to use set the following environment variables:
HWLOC     top level install location of hwloc (e.g. /usr/local)
USE_HWLOC set to 1 to use hwloc rather that linux specific hardware detection
=> Add hwloc hardware detection to realm/threads.cc.

runtime/runtime.mk
If the clean rule is changed from clean: to clean::, then users can add a clean:: rule to their projects to clean up additional files that are not cleaned by the default legion clean rule.  
An example would be cleaning up test result output.
=> Change clean rule to have double ::

runtime/runtime.mk
The -rdynamic option is not needed on OSX and does not seem to be recognized.
=> Remove -rdynamic on Darwin (OSX)

runtime/accessor.h, runtime/legion/legion_ops.cc, runtime/legion/legion_tasks.cc, runtime/legion/legion_utilities.h, runtime/legion/region_tree.cc, runtime/legion/runtime.cc, runtime/lowlevel.cc, runtime/lowlevel_disk.cc, runtime/lowlevel_dma.cc, runtime/realm/dynamic_table.inl, runtime/realm/inst_impl.cc, runtime/realm/machine_impl.cc, runtime/realm/profiling.inl, runtime/realm/rsrv_impl.cc, runtime/realm/tasks.cc, runtime/realm/threads.cc, runtime/shared_lowlevel.cc
Modifications to avoid unused variable warnings when compiling with -DNDEBUG (assertions disabled).
There are still some warnings about missing return values in functions that just have the content "assert(0);", so still can't compile with the default -Werr.
Not sure if the intrusiveness of this change is worthwhile, but if you want the changes here they are.  I won't be heartbroken if the pull request is rejected.
Also contains some variable initializations where the compiler was warning about possibly uninitialized variables.
=> Fix so can compile -DNDEBUG without unused variable warnings

runtime/runtime.mk
Use ?= instead of = in assignment of USE_LIBDL so application can override value if desired.
Also fix spelling error "falgs" to "flags"
=> Permit application makefile to override USE_LIBDL

runtime/activemsg.h
Added types.h to fix error
```shell
activemsg.h:843:9 error: 'off_t' has not been declared
```
=> Added missing sys/types.h header to fix compile error on OSX

CMakeLists.txt
=> cmake: realm/timers.cc need -fno-strict-aliasing

cmake/FindGASNet.cmake
Using $MPI_INCLUDE as a hint will help cmake to find mpi-enabled version of gasnet in Fedora.
/cc: @tuxfan
=> cmake: use $MPI_INCLUDE as hint for gasnet

cmake/FindGASNet.cmake
introduced in a76904852c60b5b2d80508e32cd69694c2aff1fc, #196
=> cmake: syntax error

cmake/FindGASNet.cmake
@junghans I think this should work for you now.  Please test to confirm.
=> CMake: Remove trailing arguments for mpicc with GASNet mpi conduit

.gitmodules
This help to inherit the same transport protocol as used for the
main repo. e.g. if https is not available (see losalamos/flecsi-third-party#11)
=> Make git submodule relative

CMakeLists.txt, cmake/legion_defines.h.in, runtime/legion/legion.h, runtime/legion/legion_tasks.cc
A fix for the CMake build issue with propagation compile-time definitions to other projects, that are built on top of the Legion:
1)  CMAKE generates legion_defines.h file where it stores all definitions
2) In case Legion is built with CMake, legion_defines.h file gets included into legion.h
@chuckatkins, @streichler : please review
=> Cmake from lanl2

runtime/realm/threads.cc
=> Realm::get_bd_sibling_id: fix return for single thread

cmake/FindGASNet.cmake
The mpi_interop example includes mpi.h and needs the MPI include path found in FindGASNet. @junghans
=> Updated FindGASNET function to add MPI include path

examples/mpi_interop/CMakeLists.txt
`mpi_interop` actively makes use of MPI, so link it against it.
=> cmake: link mpi_interop against mpi

cmake/FindGASNet.cmake
=> cmake: Link MPI when GASNet was itself linked to MPI

runtime/realm/realm_config.h
The JVM does not take kindly to non-native threads.
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
=> realm: allow uthread default override

runtime/runtime.mk
HDF_ROOT environment variable that points to the HDF5 installation directory is used if present.
=> Added ability to specify a custom HDF5 installation path

language/src/regent/pretty.t
Pretty printer now differentiates between variables with clashing names in metaprogrammed tasks (if -fdebug 0), e.g. instead of printing:
```
task foo()
var $a = 0
var $a = 0
end
```
it will print:
```
task foo()
var $a = 0
var $a#42 = 0
end
```
=> Pretty printer better variable names

bindings/python/examples/index_launch.py, bindings/python/legion.py, language/scripts/setup_env.py, language/src/regent/cudahelper.t, language/src/regent/optimize_config_options.t, language/src/regent/std.t, language/src/regent/vectorize_loops.t, language/test.py, runtime/legion/legion_c.cc, runtime/legion/legion_c.h, runtime/legion/legion_config.h, runtime/legion/legion_context.cc, runtime/legion/legion_context.h, runtime/legion/legion_ops.cc, runtime/legion/legion_ops.h, runtime/legion/legion_tasks.cc, runtime/legion/runtime.cc, runtime/realm/deppart/setops.cc, runtime/realm/inst_impl.cc, runtime/realm/operation.cc, runtime/realm/python/python_internal.h, runtime/realm/python/python_module.cc, runtime/realm/transfer/channel.cc, runtime/realm/transfer/lowlevel_dma.cc, runtime/realm/transfer/transfer.cc, runtime/realm/transfer/transfer.h, test.py
This is currently the 2nd slowest pass when compiling Soleil on my local machine (behind actual LLVM compilation):
compile 72.692785
inline_tasks 0.624195
optimize_divergence 1.045345
normalize after type check 1.723449
optimize_mapping 6.727169
skip_empty_tasks 2.743174
vectorize_loops 0.154155
parallelize_tasks 49.717688
codegen 13.026204
optimize_index_launches 6.307519
normalize after specialize 1.132306
optimize_traces 4.432626
type check 7.364484
specialize 1.237845
optimize_futures 1.045139
optimize_config_options 63.565161
check annotations 15.551507
With this patch, the running time of this pass drops almost 10x (and even parallelize_tasks seems to speed up by ~40%, although that might be a fluke):
compile 71.073906
inline_tasks 0.614681
optimize_divergence 1.047141
normalize …
=> Make optimize_config_options pass 10x faster
